"""
Django settings for devops project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '10086'
SESSION_COOKIE_AGE = 60 * 60 * 24  # token有效期
DB_WAIT_TIMEOUT = 20  # 单个连接最长维持时间
DB_POOL_SIZE = 2  # 连接池最大连接数
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 开启用户访问IP
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',         # 配置注册channels模块
]
ASGI_APPLICATION = 'devops.routing.application'

MIDDLEWARE = [
    'devops.mymiddle.CoreMiddle',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

WEB_URL = "http://182.42.126.254:8087"
ROOT_URLCONF = 'devops.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'devops.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases
ENGINE = 'django.db.backends.mysql'
# devops_orm/settings.py
DATABASES = {
	'default': {
        'ENGINE': ENGINE,
        'NAME': 'k8s',
        'USER': 'root',
        'PASSWORD': 'root1234',
        'HOST': '182.42.126.254',
        'PORT': '3306',
	},
    'web': {
        'ENGINE': ENGINE,
        'NAME': 'recruit',
        'USER': 'root',
        'PASSWORD': 'root1234',
        'HOST': '182.42.126.254',
        'PORT': '3306',
	},
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators
TOKEN = "eyJhbGciOiJSUzI1NiIsImtpZCI6IlJIbF9QUnlBTUJISkhHbzg4Wks0a3pacENBM0pZOTREVW9kc3A3d1cxak0ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJkYXNoYm9hcmQtYWRtaW4tdG9rZW4teHRycnIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGFzaGJvYXJkLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiNDg2NjczYjktNTBkMS00NjY2LTliYWMtN2ZlNjYxZGYxNDAxIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmRhc2hib2FyZC1hZG1pbiJ9.ik8OqClmZNuMUTaqX701NG2Ezsv4fB1MecYk8PsWwMYsA-r--iWVpDtuN4RnFYNvt4uBrtoIfMC3oIZfYKF1eEENQEsknuf2-GHMDrZ1zdnFDmgU7z2IFPEvtJVGankF6sjgmQGp8ymg8a72o236XzzgV2kaSNHGc6QQzuXO7_IM9UIjmrXA6lwiBv3pR_Aq3s2INxM7boTYuYUGf30anlHMQt3Wruu1OhPS9s3Vf6nOJEvlu7pGKsFwIS1xT-0rc70DwcEhl5uF36BpkW76sgt3dqVoP6N-JzxavNKZW6KF_g40Gurr8qNvJtB6KE2qerzz8PS72ct5ZzSdVWNCDg"

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

LOGIN_URL = '/login/'        # 设置默认访问页面

# 应用静态目录
STATICFILES_DIRS = (
os.path.join(BASE_DIR, 'static'),
)


# 添加redis 配置
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             "hosts": [('192.168.0.150', 6379)],
#         },
#     },
# }


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    }
}
